server:
  shutdown: GRACEFUL

spring:
  lifecycle:
    timeout-per-shutdown-phase: 40s #디폴트값은 30초
  data:
    mongodb:
#      uri: mongodb+srv://admin:내암호@cluster0.1p17esk.mongodb.net/sample_airbnb
      uri: ENC(1kiaGE3RJMoGZi9TFdjEj4IxeCJyofdL9i5bpvbN+N5pidF/5WUuNeDhGCLTXgQHUpFxFC2P1uOaEDDWv5OdLwiNVw2FT3mFNr4pB73Nb5E=)
